
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 19 20:11:19 CST 2010
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 18;
  public static final int FUNCTION = 42;
  public static final int GE = 24;
  public static final int UMINUS = 45;
  public static final int LPAREN = 8;
  public static final int INT = 4;
  public static final int ARRAY = 28;
  public static final int FOR = 33;
  public static final int MINUS = 16;
  public static final int RPAREN = 9;
  public static final int SEMICOLON = 7;
  public static final int AND = 25;
  public static final int LT = 21;
  public static final int TYPE = 44;
  public static final int NIL = 41;
  public static final int IN = 37;
  public static final int OR = 26;
  public static final int COMMA = 5;
  public static final int PLUS = 15;
  public static final int ASSIGN = 27;
  public static final int IF = 29;
  public static final int DOT = 14;
  public static final int ID = 2;
  public static final int LE = 22;
  public static final int OF = 39;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NEQ = 20;
  public static final int BREAK = 40;
  public static final int EQ = 19;
  public static final int LBRACK = 10;
  public static final int TIMES = 17;
  public static final int COLON = 6;
  public static final int LBRACE = 12;
  public static final int ELSE = 31;
  public static final int RBRACK = 11;
  public static final int TO = 34;
  public static final int WHILE = 32;
  public static final int LET = 36;
  public static final int THEN = 30;
  public static final int RBRACE = 13;
  public static final int END = 38;
  public static final int STRING = 3;
  public static final int GT = 23;
  public static final int VAR = 43;
  public static final int DO = 35;

  /* non terminals */
  static final int function_declaration = 12;
  static final int declaration = 9;
  static final int expr_list = 5;
  static final int program = 1;
  static final int empty = 3;
  static final int declaration_list = 8;
  static final int type = 13;
  static final int type_declaration = 10;
  static final int expr_seq = 6;
  static final int type_fields = 14;
  static final int $START = 0;
  static final int expr = 2;
  static final int field_list = 7;
  static final int variable_declaration = 11;
  static final int lvalue = 4;
}

